AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: production
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowCredentials: "'true'"
      # EndpointConfiguration: REGIONAL
      # Domain:
      #   DomainName: wine-emporium-api.toools.space
      #   CertificateArn: arn:aws:acm:sa-east-1:447988592397:certificate/936b6c01-bace-47e0-b976-493bd238fa09
      #   Route53:
      #     HostedZoneName: "toools.space."

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "mojo-jojo-db"
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  Handler:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-bootstrap"
      Handler: bootstrap
      CodeUri: ./bin/bootstrap.zip
      Runtime: provided.al2
      Architectures:
        - arm64
      Timeout: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: "*"
      MemorySize: 128
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ApiGatewayApi
